#!/usr/bin/env bash
set -Eeuo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE EXTENSION IF NOT EXISTS vector;

DO \\$\$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_roles WHERE rolname = '${POSTGRES_RO_USER}'
    ) THEN
        CREATE ROLE ${POSTGRES_RO_USER} LOGIN PASSWORD '${POSTGRES_RO_PASSWORD}';
    ELSE
        ALTER ROLE ${POSTGRES_RO_USER} WITH LOGIN PASSWORD '${POSTGRES_RO_PASSWORD}';
    END IF;
END
\\$\$;
SQL
