CREATE EXTENSION IF NOT EXISTS vector;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname='pop_ro') THEN CREATE ROLE pop_ro WITH LOGIN PASSWORD 'ro_secret'; END IF; END $$;
GRANT CONNECT ON DATABASE pop_estate TO pop_ro;
GRANT USAGE ON SCHEMA public TO pop_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO pop_ro;
REVOKE CREATE ON SCHEMA public FROM pop_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO pop_ro;
ALTER DEFAULT PRIVILEGES FOR ROLE pop IN SCHEMA public GRANT SELECT ON TABLES TO pop_ro;
